### ISSUE TITLE
No option "Publish coverage to bitbucket" on Branch API

### ISSUE THREAD

**Issue by JorisvanRoy** [adiesner/bitbucket-pr-coverage-status-plugin#15]
Hi,

I dont have an option for publishing the coverage to bitbucket. I have the Branch API plugin installed, version 2.6.5. What could cause this issue? I cant find a way to fix it...

**Comment by adiesner** [comment]
Hi Joris,

just for the public, I also post the information here that I just sent you via email.

It is about 4 years ago that I have last been using this plugin. We migrated from Bitbucket to Github and after a while also away from Jenkins. So no more active development on my side for this.

I wasn't able to reproduce your issue. What I did to test the plugin was:

```
cat docker-compose.yml

version: '3'
services:
  application:
    container_name: jenkins-test
    image: jenkins/jenkins
    ports:
     - "8080:8080"
    restart: always
    volumes:
        - .jenkins_home:/var/jenkins_home
```

Execute jenkins:
```
mkdir .jenkins_home && chmod 777 .jenkins_home
docker-compose up
```

After the default plugin installation I installed this plugin via:
- Downloaded the HPI from [here](https://github.com/adiesner/bitbucket-pr-coverage-status-plugin/releases/download/bitbucket-pr-coverage-status-0.0.1/bitbucket-pr-coverage-status.hpi) 
- Manage Jenkins -> Manage Plugins -> Advanced -> Deploy Plugin -> Choose file -> Deploy

And then I created a test job where I can select the "Publish coverate to bitbucket" step:
![image](https://user-images.githubusercontent.com/193293/149920615-19b7f671-162c-4696-8978-25586d5aaef5.png)

From the screenshot you sent me via email it looks like you have also installed the plugin which was the base for this plugin. I forked this project from [github-pr-coverage-status-plugin](https://github.com/jenkinsci/github-pr-coverage-status-plugin) which might be conflicting with this plugin. You might want to try to uninstall this.

I hope this helps.
Andreas
